from setuptools import setup, find_packages

setup(
    name='hs-fileinfo',
    version='1.0.0',
    description='An application that enhances file information extraction with AI-based logic improvement.',
    author='Erick Eduardo Ramirez Torres',
    author_email='erickeduardoramireztorres@gmail.com',
    url='https://github.com/eramireztorres/hs_fileinfo',
    packages=find_packages(),
    include_package_data=True,
    package_data={
        '': ['**/*.txt', 'icons/*.ico'],  # Include all .txt files and .ico files in the specified directories
    },
install_requires=[
    'google-generativeai==0.3.2',
    'tkinterdnd2==0.4.2',       
    'fpdf2==2.7.9',
    'pandas==2.2.2',
    'matplotlib==3.8.2',
    'seaborn==0.13.2',
    'plotly==5.23.0',
    'Pillow==10.4.0',
    'pydub==0.25.1',
    'nltk==3.8.1',
    'wordcloud==1.9.3',
    'pytesseract==0.3.10',
    'scipy==1.14.0',
    'librosa==0.10.2.post1',
    'PyPDF2==3.0.1',
    'pdf2image==1.17.0',
    'openpyxl==3.2.0b1',
    'python-docx==1.1.2',
    'python-pptx==1.0.0',
    'sqlalchemy==2.0.31',
    'h5py==3.11.0',
    'tqdm==4.66.5',
    'opencv-python==4.10.0.84',
    'ffmpeg-python==0.2.0',
    'moviepy==2.0.0.dev2',
    'joblib==1.4.2',
    'patool==2.3.0',
    'py7zr==0.21.1',
    'python-magic==0.4.27',
    'python-magic-bin==0.4.14',
    'rarfile==4.2',
    'xlrd==2.0.1',
    'mutagen==1.47.0',
    'cairosvg==2.7.1',
    'lxml==5.2.2',
    'odfpy==1.4.1',
    'epub==0.5.2',
    'regipy==4.3.0',
    'mido==1.3.2',
    'markdown==3.6',
    'configparser==7.0.0',
    'python-chess==1.999',
    'ebooklib==0.18',
    'svgpathtools==1.6.1',
    'selenium==4.23.1',
    'html2text==2024.2.26',
    'bs4==0.0.2',
],

    
    entry_points={
        'console_scripts': [
            'hs_fileinfo=src.fileinfo_gui:main',  # Assuming main is the function you want to execute
        ],
    },
    classifiers=[
        'Programming Language :: Python :: 3.8',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.8',
)
